core/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index,team,about,contact,search
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from .views import custom_page_not_found

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('search/', search, name='search'),  
    path('team/', team, name='team'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('main_apps.profiles.urls')),
    path('gestion/', include('main_apps.gestion.urls')),
    path('client/', include('main_apps.client.urls')),
    path('location/', include('main_apps.gestion_location.urls')),
    path('locateur/', include('main_apps.locateur.urls')),   
    path('settings/', include('main_apps.settings.urls')),
    
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Ajoutez un pattern générique pour gérer les URL non correspondantes
urlpatterns += [
    path('<path:unknown_path>', custom_page_not_found),
]

main_apps/client/urls.py
from django.urls import path
from . import views
  
app_name = 'client'  

urlpatterns = [
    
    path('', views.list_client, name='client'),
    path('ajouter_client/', views.ajouter_client, name='ajouter_client'),
    path('reservation/<int:propriete_id>/', views.reservation, name='reservation'),
    path('update_client/<int:client_id>/',views.update_client, name='update_client' ),
    path('liste_reservation/', views.liste_reservation, name='liste_reservation')
    # Ajoutez d'autres modèles d'URL au besoin
]

main_apps/client/models.py
from django.db import models
from main_apps.gestion.models import Propriete
from main_apps.profiles.models import CustomUser


# Create your models here.
class Client(models.Model):
    custom_user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=30, null=True, blank=True)
    email = models.EmailField(unique=True, null=True, blank=True)
    image = models.ImageField(upload_to='image/')
    tell = models.CharField(max_length=255)

    def __str__(self):
        return self.name



class Reservation(models.Model):
    propriete = models.ForeignKey(Propriete, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)

main_apps/client/forms.py
from django import forms
from . models import Client

class ClientForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))

class ClientUpdateForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))
   
from django import forms

class ReservationForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))
   

main_apps/client/views.py
from django.shortcuts import render,redirect
from django.shortcuts import render, get_object_or_404
from . models import Client


from main_apps.gestion.models import Propriete,Proprietaire
from . models import Reservation
from .forms import ReservationForm, ClientForm,ClientUpdateForm
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required
def list_client(request):
    
    clients = Client.objects.all()
    context = {
        'clients':clients
    }
    
    return render(request, 'client/list_client.html',context)
@login_required
def ajouter_client(request):
    if request.method == 'POST':    
        form = ClientForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            # Enregistrez le nouveau client dans la base de données
            try:
                client = Client.objects.create(
                    name=name,
                    email=email,
                )
                return redirect('gestion:home')
            except Exception as e:
                print("Erreur lors de l'enregistrement de la propriété :", e)
                # Vous pouvez ajouter d'autres messages de débogage si nécessaire
        else:
            print("Formulaire invalide :", form.errors)
    else:
        form = ClientForm()

    context = {'form': form}
    return render(request, 'client/ajouter_client.html', context)

@login_required
def update_client(request,client_id):
    client = get_object_or_404(Client,id=client_id)
    
    if request.method == 'POST':
        form = ClientUpdateForm(request.POST,  instance=client)
        if form.is_valid():
            form.save()
            return redirect('gestion:home') 
    else:
        form = ClientUpdateForm()  # Remplir le formulaire avec les données existantes

    return render(request, 'client/update_client.html', context={'form': form})
@login_required
def supprimer_client(request):
    
    return render(request, 'client/supprimer_client.html')

from django.shortcuts import render, get_object_or_404, redirect


from .forms import ReservationForm

from django.shortcuts import render, get_object_or_404, redirect
from .models import Propriete, Client, Reservation
from .forms import ReservationForm

from django.shortcuts import render, get_object_or_404, redirect
from .models import Propriete, Reservation, Client
from .forms import ReservationForm
from django.contrib.auth.decorators import login_required

@login_required
def reservation(request, propriete_id):
    propriete = get_object_or_404(Propriete, pk=propriete_id)

    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            # Récupérez les informations du formulaire
            client, created = Client.objects.get_or_create(
                email=form.cleaned_data['email'],
                defaults={'name': form.cleaned_data['name']}
            )
           
            # Créez la réservation avec la propriété et le client
            try:
                reservation = Reservation.objects.create(
                    propriete=propriete,
                    client=client
                )
                
                # Mettez à jour le statut de la propriété
                propriete.statut = 'indisponible'
                propriete.save()

                return redirect('locateur:lien_conf')  # Redirige vers une page de confirmation de réservation
            except Exception as e:
                print("Erreur lors de l'enregistrement de la propriété :", e)
                # Vous pouvez ajouter d'autres messages de débogage si nécessaire
        else:
            print("Formulaire invalide :", form.errors)
            # Traitez le cas où le formulaire n'est pas valide, par exemple, en renvoyant le formulaire avec des erreurs

    else:
        form = ReservationForm()

    context = {
        'propriete': propriete,
        'form': form
    }

    return render(request, 'client/reservation.html', context)

@login_required
def liste_reservation(request):
    
    reservations = Reservation.objects.all()
    
    context = {
        'reservations':reservations
    }
    
    return render(request, 'reservation/liste_reservation.html', context)

templates/client/ajouter_client.html
{% extends '_base.html' %} {% block content %}
    
<section class="bg-white dark:bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
        <h2 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Add a new product</h2>
        <form  method="post" action="{% url 'client:ajouter_client' %}">
            {% csrf_token %}
            <!-- component -->
<div class=" w-full flex items-center justify-center text-blue-600 bg-white dark:bg-gray-900">
    <div>
      <h1 class="mb-1 font-bold text-3xl flex gap-1 items-baseline font-mono">Form UI<span class="text-sm text-purple-700">form showcase</sm></h1>
        <div class="grid max-w-3xl gap-2 py-10 px-8 sm:grid-cols-2 bg-white dark:bg-gray-900 rounded-md border-t-4 border-blue-600">
          <form  method="post">
            {% csrf_token %}
              <div class="w-full  items-center justify-center grid gap-4 mb-4 sm:grid-cols-2">
                  <div>
                      <label for="{{ form.name.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nom</label>
                      {{form.name}}
                  </div>
                <div>
                    <label for="{{ form.email.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Email</label>
                    {{form.email}}
                </div>
              </div>
              <div class="flex items-center space-x-4">
                <div  class="text-sm text-gray-600 dark:text-gray-400" href="#">
                      <button type="submit" class="text-gray-300 inline-flex items-center hover:text-white border border-blue-600 hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-900">
                        Ajouter Client
                    </button>                                       
                </div>

              </div>
          </form>
          </div>
          </div>
        </form>
    </div>
</section>

{% endblock content %}
    

templates/client/reservation.html
{% extends 'base2.html' %} {% block content %}

<section class="bg-white white:bg-gray-700 rounded-lg">
    <!-- Card Section -->
    <div class="max-w-5xl px-4 py-10 sm:px-6 lg:px-8 lg:py-14 mx-auto">
        <!-- Grid -->
        <div class="container mx-auto py-8 px-4 md:px-0">
            <div class="md:max-w-5xl mx-auto mt-5">
                <div class="grid grid-cols-3 gap-4">
                    <div class="col-span-1">
                        <nav class="bg-white shadow rounded-lg border-gray-50">
                            <a href="#" class="rounded-t group flex items-center px-3 py-2 leading-5 focus:outline-none transition ease-in-out duration-150 border-r-4 border-indigo-500 text-md font-semibold text-indigo-500">
                                Faire une reservation
                            </a>
                            <a href="#" class="rounded-t group flex items-center px-3 py-2 leading-5 focus:outline-none transition ease-in-out duration-150  border-r-4 border-indigo-500 text-md font-medium text-indigo-500  hover:text-gray-600 ">
                                Pour {{ propriete.type_propriete }}
                            </a>
                        </nav>
                    </div>
                    <div class="col-span-1">
                        <ul class="space-y-4">
                            <li class="bg-gray-400 white:bg-gray-700 shadow  border-r-4 border-indigo-500 overflow-hidden rounded-md">
                                <a href="#" class="block hover:bg-gray-50 focus:outline-none focus:bg-gray-50 transition duration-150 ease-in-out">
                                    <div class="px-4 py-4 flex items-center sm:px-6">
                                        <div class="min-w-0 flex-1 sm:flex sm:items-center sm:justify-between">
                                            <div>
                                                <div class="mt-2 flex ">

                                                    <ul class="space-y-4 text-left rounded text-gray-500 bg-white white:bg-gray-700">
                                                        <li class="flex px-4 py-2 items-center  rounded space-x-3 rtl:space-x-reverse hover:bg-gray-300 white:hover:bg-indigo-600 white:hover:text-white">
                                                            <svg class="flex-shrink-0 w-3.5 h-3.5 text-green-500 white:text-green-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 12">
                                                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5.917 5.724 10.5 15 1.5"/>
                                                             </svg>
                                                            <span>{{propriete.titre}}</span>
                                                        </li>
                                                        <li class="flex px-4 py-2 items-center  rounded space-x-3 rtl:space-x-reverse hover:bg-gray-300 white:hover:bg-indigo-600 white:hover:text-white">
                                                            <svg class="flex-shrink-0 w-3.5 h-3.5 text-green-500 white:text-green-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 12">
                                                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5.917 5.724 10.5 15 1.5"/>
                                                             </svg>
                                                            <span>{{propriete.statut}}</span>
                                                        </li>
                                                        <li class="flex px-4 py-2 items-center  rounded space-x-3 rtl:space-x-reverse hover:bg-gray-300 white:hover:bg-indigo-600 white:hover:text-white">
                                                            <svg class="flex-shrink-0 w-3.5 h-3.5 text-green-500 white:text-green-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 12">
                                                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5.917 5.724 10.5 15 1.5"/>
                                                             </svg>
                                                            <span>{{propriete.adresse}}</span>
                                                        </li>
                                                        <li class="flex px-4 py-2 items-center  rounded space-x-3 rtl:space-x-reverse hover:bg-gray-300 white:hover:bg-indigo-600 white:hover:text-white">
                                                            <svg class="flex-shrink-0 w-3.5 h-3.5 text-green-500 white:text-green-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 12">
                                                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5.917 5.724 10.5 15 1.5"/>
                                                             </svg>
                                                            <span>{{propriete.description}}</span>
                                                        </li>
                                                        <li class="flex px-4 py-2 items-center  rounded space-x-3 rtl:space-x-reverse hover:bg-gray-300 white:hover:bg-indigo-600 white:hover:text-white">
                                                            <svg class="flex-shrink-0 w-3.5 h-3.5 text-green-500 white:text-green-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 12">
                                                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5.917 5.724 10.5 15 1.5"/>
                                                             </svg>
                                                            <span>Nombre des chambres: <span class="font-semibold text-gray-900 white:text-white">{{propriete.nombre_chambres}}</span></span>
                                                        </li>
                                                        <li class="flex px-4 py-2 items-center  rounded space-x-3 rtl:space-x-reverse hover:bg-gray-300 white:hover:bg-indigo-600 white:hover:text-white">
                                                            <svg class="flex-shrink-0 w-3.5 h-3.5 text-green-500 white:text-green-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 12">
                                                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5.917 5.724 10.5 15 1.5"/>
                                                             </svg>
                                                            <span>Nre des salles des bains: <span class="font-semibold text-gray-900 white:text-white">{{propriete.nombre_salles_bains}}</span></span>
                                                        </li>
                                                        <li class="flex px-4 py-2 items-center  rounded space-x-3 rtl:space-x-reverse hover:bg-gray-300 white:hover:bg-indigo-600 white:hover:text-white">
                                                            <svg class="flex-shrink-0 w-3.5 h-3.5 text-green-500 white:text-green-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 12">
                                                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5.917 5.724 10.5 15 1.5"/>
                                                             </svg>
                                                            <span>Surface en m2: <span class="font-semibold text-gray-900 white:text-white">{{propriete.surface_m2}}</span></span>
                                                        </li>
                                                        <li class="flex px-4 py-2 items-center  rounded space-x-3 rtl:space-x-reverse hover:bg-gray-300 white:hover:bg-indigo-600 white:hover:text-white">
                                                            <svg class="flex-shrink-0 w-3.5 h-3.5 text-green-500 white:text-green-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 12">
                                                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5.917 5.724 10.5 15 1.5"/>
                                                             </svg>
                                                            <span>{{propriete.prix}} GNF</span>
                                                        </li>
                                                    </ul>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Grid -->
    </div>
    <!-- End Card Section -->
    <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16 bg-white white:bg-gray-700 border-blue-600">
        <form method="post" action="{% url 'client:reservation' propriete.id %}">
            {% csrf_token %}
            <div class="w-full flex items-center justify-center text-blue-600 bg-white white:bg-gray-700 ">
                <div>
                    <h1 class="mb-1 font-bold text-3xl flex gap-1 items-baseline font-mono">Form UI<span class="text-sm text-purple-700">form showcase</span></h1>
                    <div class="grid max-w-3xl gap-2 py-10 px-8 sm:grid-cols-2 bg-gray-100 rounded-md border-t-4 border-blue-600">
                        <div class="w-full items-center justify-center grid gap-4 mb-4 sm:grid-cols-2">
                            <div>
                                <label for="{{ form.name.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 white:text-white">Nom</label>
                                <input type="text" name="{{ form.name.name }}" id="{{ form.name.id_for_label }}" value="{{ form.name.value }}" class="py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 white:bg-gray-800 white:border-gray-700 white:text-gray-400">                                {% if form.name.errors %}
                                <p class="text-red-500 text-sm mt-1">{{ form.name.errors }}</p>
                                {% endif %}
                            </div>
                            <div>
                                <label for="{{ form.email.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 white:text-white">Email</label>
                                <input type="email" name="{{ form.email.name }}" id="{{ form.email.id_for_label }}" value="{{ form.email.value }}" class="py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 white:bg-gray-800 white:border-gray-700 white:text-gray-400">                                {% if form.email.errors %}
                                <p class="text-red-500 text-sm mt-1">{{ form.email.errors }}</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="flex items-center space-x-4">
                            <div class="text-sm text-gray-600 white:text-gray-400">
                                <button type="submit" class="text-gray-300 inline-flex items-center hover:text-white border border-blue-600 hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center white:border-blue-500 white:text-blue-500 white:hover:text-white white:hover:bg-blue-600 white:focus:ring-blue-900">
                                    Faire une reservation
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

    </div>

</section>



{% endblock content %}

templates/client/update_client.html
{% extends '_base.html' %} {% block content %}
    
<section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
        <h2 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Add a new product</h2>
        <form  method="post" action="{% url 'client:ajouter_client' %}">
            {% csrf_token %}
            <!-- component -->
<div class=" w-full flex items-center justify-center text-blue-600 bg-gray-900">
    <div>
      <h1 class="mb-1 font-bold text-3xl flex gap-1 items-baseline font-mono">Form UI<span class="text-sm text-purple-700">form showcase</sm></h1>
        <div class="grid max-w-3xl gap-2 py-10 px-8 sm:grid-cols-2 bg-gray-900 rounded-md border-t-4 border-blue-600">
          <form  method="post">
            {% csrf_token %}
              <div class="w-full  items-center justify-center grid gap-4 mb-4 sm:grid-cols-2">
                  <div>
                      <label for="{{ form.name.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nom</label>
                      {{form.name}}
                  </div>
                <div>
                    <label for="{{ form.email.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Email</label>
                    {{form.email}}
                </div>
              </div>
              <div class="flex items-center space-x-4">
                <div  class="text-sm text-gray-600 dark:text-gray-400" href="#">
                      <button type="submit" class="text-gray-300 inline-flex items-center hover:text-white border border-blue-600 hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-900">
                        Ajouter Client
                    </button>                                       
                </div>

              </div>
          </form>
          </div>
          </div>
        </form>
    </div>
</section>

{% endblock content %}
    