core/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index,team,about,contact,search
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from .views import custom_page_not_found

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('search/', search, name='search'),  
    path('team/', team, name='team'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('main_apps.profiles.urls')),
    path('gestion/', include('main_apps.gestion.urls')),
    path('client/', include('main_apps.client.urls')),
    path('location/', include('main_apps.gestion_location.urls')),
    path('locateur/', include('main_apps.locateur.urls')),   
    path('settings/', include('main_apps.settings.urls')),
    
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Ajoutez un pattern générique pour gérer les URL non correspondantes
urlpatterns += [
    path('<path:unknown_path>', custom_page_not_found),
]

main_apps/client/urls.py
from django.urls import path
from . import views
  
app_name = 'client'  

urlpatterns = [
    
    path('', views.list_client, name='client'),
    path('ajouter_client/', views.ajouter_client, name='ajouter_client'),
    path('reservation/<int:propriete_id>/', views.reservation, name='reservation'),
    path('update_client/<int:client_id>/',views.update_client, name='update_client' ),
    path('liste_reservation/', views.liste_reservation, name='liste_reservation')
    # Ajoutez d'autres modèles d'URL au besoin
]

main_apps/gestion/urls.py
from django.urls import path
from . import views
app_name = 'gestion'

urlpatterns = [
    
    path('', views.home, name='home'),
    path('list_users/', views.list_users, name='users'),
    path('ajouter_proprietaire/', views.ajouter_proprietaire, name='ajouter_proprietaire'),
    path('liste_proprietaires/', views.liste_proprietaires, name='liste_proprietaires'),
    path('update_proprietaire/<int:proprietaire_id>/', views.update_proprietaire, name='update_proprietaire'),
    path('supprimer_proprietaire/<int:proprietaire_id>/', views.supprimer_proprietaire, name='supprimer_proprietaire'),
    path('ajouter_propriete/', views.ajouter_propriete, name='ajouter_propriete'),
    path('update_propriete/<int:propriete_id>/', views.update_propriete, name='update_propriete'),
    path('supprimer_propriete/<int:propriete_id>/', views.supprimer_propriete, name='supprimer_propriete'),
    path('details_list/<int:propriete_id>/', views.details_list, name='details_list'),
    
    
#    path('delete_user/<int:user_id>/', views.delete_profile, name='delete_profile'),
]

main_apps/gestion/forms.py
from django import forms
from .models import Proprietaire,Propriete



from django import forms


    
class ProprietaireForm(forms.Form):
    
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))
    s_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))
    numero_telephone = forms.CharField(widget=forms.TextInput(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))
    adresse = forms.CharField(widget=forms.TextInput(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))
   


from django import forms
from .models import Propriete

from django import forms

CHOIX_SURFACE = [
    ('60', '60 m2'),
    ('80', '80 m2'),
    ('100', '100 m2'),
    # ... autres options ...
]

class ProprieteForm(forms.Form):
    titre = forms.CharField(widget=forms.TextInput(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))
    adresse = forms.CharField(widget=forms.TextInput(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))
    description = forms.CharField(widget=forms.TextInput(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))
    prix = forms.CharField(widget=forms.TextInput(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))

   
    proprietaire = forms.ModelChoiceField(
        queryset=Proprietaire.objects.all(),
        widget=forms.Select(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'})
    )
    
    statut = forms.ChoiceField( choices=[('indisponible', 'Indisponible'),('disponible', 'Disponible'), ('loue', 'Loué'), ('vente', 'En vente')], widget=forms.Select(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))
    type_propriete = forms.ChoiceField( choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('terrain', 'Terrain'), ('autre', 'Autre')], widget=forms.Select(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))
    nombre_chambres = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))
    nombre_salles_bains = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))
    surface_m2 = forms.ChoiceField(choices=CHOIX_SURFACE, widget=forms.Select(attrs={'class': 'py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400'}))

main_apps/gestion/views.py
from django.shortcuts import redirect, render
from .models import Proprietaire,Propriete
from main_apps.gestion.forms import ProprieteForm,ProprietaireForm
from django.core.paginator import Paginator

from django.core.paginator import Paginator
from django.shortcuts import render
from .models import Proprietaire, Propriete
from main_apps.client.models import Client,Reservation
from datetime import datetime
from django.contrib.auth.decorators import login_required
from .models import RecentActivity
from main_apps.profiles.models import CustomUser

from django.contrib.sessions.models import Session
from django.contrib.auth.models import User
from django.utils import timezone

@login_required
def home(request):
    
    # Récupérer toutes les sessions actives dans une liste de dictionnaires
    sessions = Session.objects.filter(expire_date__gte=timezone.now())
    
    # Extraire les identifiants d'utilisateur de toutes les sessions actives
    user_ids = [session.get_decoded().get('_auth_user_id') for session in sessions]

    # Filtrer les utilisateurs uniques et récupérer leurs instances depuis la base de données
    logged_in_users = CustomUser.objects.filter(id__in=user_ids)
    
    ###########################################################################
    recent_activities = RecentActivity.objects.all().order_by('-timestamp')[:6] 
    proprietes = Propriete.objects.all()
    proprietaires = Proprietaire.objects.all()
    
    total_proprietaires = Proprietaire.objects.count()
    total_proprietes = Propriete.objects.count()
    total_client = Client.objects.count()
    total_reservation = Reservation.objects.count()

    paginator = Paginator(proprietaires, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    # Détermination du message de salutation en fonction de l'heure
    current_time = datetime.now()
    hour = current_time.hour
    greeting = "Bonjour" if 6 <= hour < 12 else "Bonsoir"

    context = {
        'logged_in_users': logged_in_users,
        'proprietes': proprietes,
        'proprietaires': page_obj,
        'total_proprietaires': total_proprietaires,
        'total_proprietes': total_proprietes,
        'page_obj': page_obj,
        'total_client': total_client,
        'total_reservation': total_reservation,
        'greeting': greeting,
        'recent_activities': recent_activities,
    }

    return render(request, 'gestion/home.html', context)

########################################################################################
from django.shortcuts import redirect, render
from .forms import ProprietaireForm
from .models import CustomUser, Proprietaire

@login_required
def ajouter_proprietaire(request):
    if request.method == "POST":
        form = ProprietaireForm(request.POST)
        if form.is_valid():
            # Récupérer les données du formulaire
            username = form.cleaned_data['username']
            s_name = form.cleaned_data['s_name']
            numero_telephone = form.cleaned_data['numero_telephone']
            adresse = form.cleaned_data['adresse']
            email = form.cleaned_data['email']
            
            #Vérifier si l'utilisateur personnalisé existe déjà
            custom_user, created = CustomUser.objects.get_or_create(email=email, defaults={
                'username': username,
                's_name': s_name,
                'numero_telephone': numero_telephone
            })

            # Créer le propriétaire associé au CustomUser
            proprietaire, created = Proprietaire.objects.get_or_create(custom_user=custom_user, adresse=adresse)
            return redirect('gestion:home')
    else:
        form = ProprietaireForm()

    context = {'form': form}
    return render(request, 'gestion/ajouter_proprietaire.html', context)

# ########################################################################################
# @login_required
# def ajouter_proprietaire(request):
#     if request.method == "POST":
#         form = ProprietaireForm(request.POST)
#         if form.is_valid():
#             # Récupérez les données du formulaire
#             username = form.cleaned_data['username']
#             s_name = form.cleaned_data['s_name']
#             numero_telephone = form.cleaned_data['numero_telephone']
#             adresse = form.cleaned_data['adresse']
#             email = form.cleaned_data['email']
            
#             # Vérifiez si l'utilisateur personnalisé existe déjà
#             custom_user, created = CustomUser.objects.get_or_create(email=email, defaults={
            
#                 'username': username,
#                 's_name': s_name,
#                 'numero_telephone': numero_telephone
#             })

#             # Créez le propriétaire associé au CustomUser
#             proprietaire, created = Proprietaire.objects.get_or_create(custom_user=custom_user, adresse=adresse)
#             return redirect('gestion:home')
#     else:
#         form = ProprietaireForm()

#     context = {'form': form}
#     return render(request, 'gestion/ajouter_proprietaire.html', context)

@login_required
def liste_proprietaires(request):
    
    proprietaires = Proprietaire.objects.all()
    
    context = {
        'proprietaires':proprietaires
    }
    
    return render(request, 'gestion/liste_proprietaires.html', context)     
        

################################### update # profile ####################################

from django.shortcuts import render, get_object_or_404
from .forms import ProprietaireForm
from .models import Proprietaire
@login_required
def update_proprietaire(request, proprietaire_id):
    proprietaire = get_object_or_404(Proprietaire, id=proprietaire_id)
    
    if request.method == 'POST':
        form = ProprietaireForm(request.POST, instance=proprietaire)
        if form.is_valid():
            form.save()
            return redirect('gestion:home')  # Rediriger vers la page d'accueil après la mise à jour
    else:
        form = ProprietaireForm()  # Remplir le formulaire avec les données existantes

    return render(request, 'gestion/update_proprietaire.html', context={'form': form})

@login_required
def supprimer_proprietaire(request, proprietaire_id):
    proprietaire = get_object_or_404(Proprietaire, id=proprietaire_id)
    
    if request.method == 'POST':
        proprietaire.delete()
        return redirect('gestion:home')  # Rediriger vers la page d'accueil après la suppression
    
    return render(request, 'gestion/supprimer_proprietaire.html', context={'proprietaire': proprietaire})

    

from django.shortcuts import render, redirect
from .forms import ProprieteForm
from .models import Propriete
@login_required
def ajouter_propriete(request):
    if request.method == 'POST':    
        form = ProprieteForm(request.POST)
        if form.is_valid():
            # Créez une nouvelle instance du modèle Propriete avec les données du formulaire        
            titre = form.cleaned_data['titre']
            adresse = form.cleaned_data['adresse']
            description = form.cleaned_data['description']
            prix = form.cleaned_data['prix']
            proprietaire = form.cleaned_data['proprietaire']
            statut = form.cleaned_data['statut']
            type_propriete = form.cleaned_data['type_propriete']
            nombre_chambres = form.cleaned_data['nombre_chambres']
            nombre_salles_bains = form.cleaned_data['nombre_salles_bains']
            surface_m2 = form.cleaned_data['surface_m2']

            # Enregistrez la nouvelle propriété dans la base de données
            try:
                propriete = Propriete.objects.create(
                    titre=titre,
                    adresse=adresse,
                    description=description,
                    prix=prix,
                    proprietaire=proprietaire,
                    statut=statut,
                    type_propriete=type_propriete,
                    nombre_chambres=nombre_chambres,
                    nombre_salles_bains=nombre_salles_bains,
                    surface_m2=surface_m2
                )
                return redirect('gestion:home')
            except Exception as e:
                print("Erreur lors de l'enregistrement de la propriété :", e)
                # Vous pouvez ajouter d'autres messages de débogage si nécessaire
        else:
            print("Formulaire invalide :", form.errors)
    else:
        form = ProprieteForm()

    context = {'form': form}
    return render(request, 'gestion/ajouter_propriete.html', context)
################################ Update propriete ##################################################################
@login_required
def update_propriete(request, propriete_id):
    propriete = get_object_or_404(Propriete, id=propriete_id)
    
    if request.method == 'POST':
        form = ProprieteForm(request.POST, instance=propriete)
        if form.is_valid():
            form.save()
            return redirect('gestion:home')  # Rediriger vers la page d'accueil après la mise à jour
    else:
        form = ProprieteForm()  # Remplir le formulaire avec les données existantes

    return render(request, 'gestion/update_propriete.html', context={'form': form})
@login_required
def supprimer_propriete(request, propriete_id):
    propriete = get_object_or_404(Propriete, id=propriete_id)
    
    if request.method == 'POST':
        propriete.delete()
        return redirect('gestion:home')  # Rediriger vers la page d'accueil après la suppression
    
    return render(request, 'gestion/supprimer_propriete.html', context={'propriete': propriete})

@login_required
def details_list(request, propriete_id):
    propriete = get_object_or_404(Propriete, id=propriete_id)
    return render(request, 'gestion/details_list.html', {'propriete': propriete})
@login_required
def list_users(request):
    return render(request,'gestion/list_users.html')

templates/gestion/ajouter_proprietaire.html
{% extends '_base.html' %} {% block content %}
    
<section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
        <h2 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Add a new product</h2>
        <form  method="post" action="{% url 'gestion:ajouter_proprietaire' %}">
            {% csrf_token %}
            <!-- component -->
<div class=" w-full flex items-center justify-center text-blue-600 bg-white dark:bg-gray-900">
    <div>
      <h1 class="mb-1 font-bold text-3xl flex gap-1 items-baseline font-mono">Form UI<span class="text-sm text-purple-700">form showcase</sm></h1>
        <div class="grid max-w-3xl gap-2 py-10 px-8 sm:grid-cols-2 bg-white dark:bg-gray-900 rounded-md border-t-4 border-blue-600">
          <form  method="post">
            {% csrf_token %}
              <div class="w-full  items-center justify-center grid gap-4 mb-4 sm:grid-cols-2">
                  <div>  
                      <label for="{{ form.username.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nom</label>
                      {{form.username}}
                  </div>
                  <div>
                      <label for="{{ form.s_name.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Prenom</label>
                     {{form.s_name}}
                  </div>
                  <div>
                    <label for="{{ form.numero_telephone.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Numero telephone</label>
                    {{form.numero_telephone}}
                </div>
                <div>
                    <label for="{{ form.adresse.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Adresse</label>
                    {{form.adresse}}
                </div>
                <div>
                    <label for="{{ form.email.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Email</label>
                    {{form.email}}
                </div>
              </div>
              <div class="flex items-center space-x-4">
                <div  class="text-sm text-gray-600 dark:text-gray-400" href="#">
                      <button type="submit" class="text-gray-300 inline-flex items-center hover:text-white border border-blue-600 hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-900">
                        Ajouter proprietaire
                    </button>                                       
                </div>

              </div>
          </form>
          </div>
          </div>
        </form>
    </div>
</section>

{% endblock content %}
    

templates/gestion/ajouter_propriete.html
{% extends '_base.html' %} {% block content %}
    
<section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
        <h2 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Ajouter une nouvelle propriété</h2>
        <form method="post" action="{% url 'gestion:ajouter_propriete' %}">
            {% csrf_token %}
            <div class="w-full flex items-center justify-center text-blue-600 bg-white dark:bg-gray-900">
                <div>
                    <h1 class="mb-1 font-bold text-3xl flex gap-1 items-baseline font-mono">Form UI<span class="text-sm text-purple-700">form showcase</span></h1>
                    <div class="grid max-w-3xl gap-2 py-10 px-8 sm:grid-cols-2 bg-white dark:bg-gray-900 rounded-md border-t-4 border-blue-600">
                        <div class="w-full items-center justify-center grid gap-4 mb-4 sm:grid-cols-2">
                            <div>
                                <label for="{{ form.titre.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Titre</label>
                                {{ form.titre }}
                            </div>
                            <div>
                                <label for="{{ form.adresse.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Adresse</label>
                                {{ form.adresse }}
                            </div>
                            <div>
                                <label for="{{ form.description.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
                                {{ form.description }}
                            </div>
                            <div>
                                <label for="{{ form.prix.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Prix</label>
                                {{ form.prix }}
                            </div>
                            <div>
                                <label for="{{ form.proprietaire.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Propriétaire</label>
                                {{ form.proprietaire }}
                            </div>
                            <div>
                                <label for="{{ form.statut.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Statut</label>
                                {{ form.statut }}
                            </div>
                            <div>
                                <label for="{{ form.type_propriete.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Type de propriété</label>
                                {{ form.type_propriete }}
                            </div>
                            <div>
                                <label for="{{ form.nombre_chambres.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nombre de chambres</label>
                                {{ form.nombre_chambres }}
                            </div>
                            <div>
                                <label for="{{ form.nombre_salles_bains.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nombre de salles de bains</label>
                                {{ form.nombre_salles_bains }}
                            </div>
                            <div>
                                <label for="{{ form.surface_m2.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Surface en m²</label>
                                {{ form.surface_m2 }}
                            </div>
                        </div>
                        <div class="flex items-center space-x-4">
                            <div class="text-sm text-gray-600 dark:text-gray-400">
                                <button type="submit" class="text-gray-300 inline-flex items-center hover:text-white border border-blue-600 hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-900">
                                    Ajouter propriété
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>


{% endblock content %}
    

templates/gestion/propriete.html
{% extends 'base2.html' %} {% block content %}


<tbody id="todo-results">
{% for propriete in proprietes %}
  <tr
    class="bg-white lg:hover:bg-gray-100 flex lg:table-row flex-row lg:flex-row flex-wrap lg:flex-no-wrap mb-10 lg:mb-0">
    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
      {{propriete.title}}
    </td>
    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
      {% if propriete.completed %}
        <span class="rounded bg-green-400 py-1 px-3 text-xs font-bold">Yes</span>
      {% else %}
        <span class="rounded bg-red-400 py-1 px-3 text-xs font-bold">No</span>
      {% endif %}
    </td>
  </tr>
{% endfor %}
</tbody>

    
{% endblock content %}
    

templates/gestion/update_proprietaire.html
{% extends '_base.html' %} {% block content %}
    
<section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
        <h2 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Add a new product</h2>
        <form  method="post" action="{% url 'gestion:ajouter_proprietaire' %}">
            {% csrf_token %}
            <!-- component -->
<div class=" w-full flex items-center justify-center text-blue-600 bg-gray-900">
    <div>
      <h1 class="mb-1 font-bold text-3xl flex gap-1 items-baseline font-mono">Form UI<span class="text-sm text-purple-700">form showcase</sm></h1>
        <div class="grid max-w-3xl gap-2 py-10 px-8 sm:grid-cols-2 bg-gray-900 rounded-md border-t-4 border-blue-600">
            <form method="post" class="grid gap-4 mb-4 sm:grid-cols-2">
                {% csrf_token %}
                <div>
                    <label for="{{ form.username.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Username</label>
                    {{ form.username }}
                </div>
                <div>
                    <label for="{{ form.s_name.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Prénom</label>
                    {{ form.s_name }}
                </div>
                <div>
                    <label for="{{ form.numero_telephone.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Numéro de téléphone</label>
                    {{ form.numero_telephone }}
                </div>
                <div>
                    <label for="{{ form.adresse.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Adresse</label>
                    {{ form.adresse }}
                </div>
                <div>
                    <label for="{{ form.email.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Email</label>
                    {{ form.email }}
                </div>
                <div class="col-span-2">
                    <button type="submit" class="text-white bg-blue-600 border border-blue-600 hover:bg-blue-700 focus:ring-4 focus:ring-blue-300 rounded-lg px-5 py-2 text-center">
                        Ajouter propriétaire
                    </button>
                </div>
            </form>
            
          </div>
          </div>
        </form>
    </div>
</section>

{% endblock content %}
    